- name: variables from files
  hosts: web
  vars_files:
  - 04-variables.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
